[package]
name = "shambler"
version = "0.1.1"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
rayon = "1.8.0"
shalrath = "0.2.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
usage = { version = "1.4.0", features = ["rayon"] }
